services:
    nginx:
        image: 'nginx:alpine'
        container_name: devstagram_nginx
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - './:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - devstagram
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: devstagram_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './:/var/www'
        networks:
            - devstagram
        depends_on:
            - db
            - redis
    db:
        image: 'mysql:8.0'
        container_name: devstagram_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: devstagram
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: laravel
        volumes:
            - 'mysql_data:/var/lib/mysql'
        ports:
            - '3306:3306'
        networks:
            - devstagram
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    redis:
        image: 'redis:alpine'
        container_name: devstagram_redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - devstagram
    phpmyadmin:
        image: phpmyadmin
        container_name: devstagram_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: laravel
            PMA_PASSWORD: password
        ports:
            - '8081:80'
        depends_on:
            - db
        networks:
            - devstagram
volumes:
    mysql_data:
        driver: local
networks:
    devstagram:
        driver: bridge